### ISSUE TITLE
Errors in running pathCV example

### ISSUE THREAD

**Issue by wzhou19** [Colvars/colvars#263] opened 2019-07-01 18:48 UTC
Hi all,

I'm running pathCV example from https://github.com/Colvars/colvars/blob/master/examples/10_pathCV.namd and related tcl script from https://github.com/Colvars/colvars/blob/master/colvartools/pathCV.tcl. I tried it on both single and multiple processors and encountered the same error

```
colvars: Error while executing calc_pathCVs {3.40183376140291e-05} {9.65155810367542e-01}:
colvars: can't use empty string as operand of "+"
```
The error is located at line 69 of the file "pathCV.tcl"
`set max [expr {[lindex $sorted [expr {$min_images - 1}]] + 1e-12}]`

In my test, I have 2 images and I'm trying to move the system from one to the other. Has anyone encountered such an issue before? 

Thanks,
Wenchang

**Comment by wzhou19** [comment] 2019-07-02 20:04
Some updates on my issue, since I only have start and end point, two images, I tuned the min_images from the default 4 to 2, the code is now working!

**Comment by jhenin** [comment] 2019-07-03 13:27
Thank you @wzhou19  for the update, this made it easier for me to propose the fix that I just committed. Can you please check that it works with your initial input?

**Comment by wzhou19** [comment] 2019-07-03 14:57
I still haven't gone through. In my initial input, I set freq=20 and min_images=4.

In the new code
```
   if { [ expr {($step % $freq) == 0 }]} {
        # Sanity check for paths with very few images
        if { $N < $min_images } { set min_images $N }

```
I need to set freq=1 so that min_images can be modified by variable $args


After I modified freq to 1, I have the following error:
```
colvars: Error while executing calc_pathCVs {3.40183376140291e-05} {9.65155810367542e-01}:
colvars: can't read "flags": no such variable
FATAL ERROR: Error in the collective variables module: Inappropriate ioctl for device

```

**Comment by jhenin** [comment] 2019-07-05 12:31
Hi @wzhou19 , I made the behavior more robust to somewhat unusual cases: few images, and no adaptive selection of images (which potentially go together).

**Comment by wzhou19** [comment] 2019-07-05 13:14
Hi @jhenin, there is one more issue with the updated tcl script:
```
colvars: PathCV FATAL ERROR: min_images cannot be more (4) than the total number of images (2).
TCL: Exiting due to exit command.

```

**Comment by jhenin** [comment] 2019-07-09 13:44
Hi @wzhou19 , that is the intended behavior: the script is showing an error when it detects inconsistent parameters. You need to change the value of min_images.

**Comment by wzhou19** [comment] 2019-07-09 14:57
Hi @jhenin, thanks for your help. The current version works.

**Closed** 2019-07-15 19:06 UTC
