### ISSUE TITLE
Adding interface to return uniform pRNG to colvarproxy

### ISSUE THREAD

**Issue by akohlmey** [Colvars/colvars#45] opened 2015-10-13 15:39 UTC
The code at:
https://github.com/colvars/colvars/blob/master/src/colvarbias_alb.cpp#L209

``` c++
      //stochastic if we do that update or not
      if (colvars.size() == 1 || rand() < RAND_MAX / ((int) colvars.size())) {
        coupling_accum[i] += step_size * step_size;
        current_coupling[i] = set_coupling[i];
        set_coupling[i] += max_coupling_range[i] / sqrt(coupling_accum[i]) * step_size;
        coupling_rate[i] = (set_coupling[i] - current_coupling[i]) / update_freq;
        //set to the minimum rate and then put the sign back on it
        coupling_rate[i] = copysign(fmin(fabs(coupling_rate[i]), max_coupling_rate[i]), coupling_rate[i]);
      } else {
        coupling_rate[i] = 0;
      }
```

uses the pRNG from the system library (which may be of questionable quality). Wouldn't it be cleaner to add an interface to a uniform pRNG to the colvarproxy class? same as for gaussian distributed? return value would be a cvm::real between 0.0 and 1.0.

**Comment by giacomofiorin** [comment] 2015-10-13 15:45
The colvarproxy class already has a rand_gaussian() function, I believe it is only the ALB code that doesn't use it.

**Comment by akohlmey** [comment] 2015-10-13 15:52
Well, my point is that if it uses rand() it will use a __uniform__ distributed pseudo random number, which rand_gaussian() doesn't provide. Hence the question about leaving this *as is* or adding an API. Or are you implying that this code __should__ use the gaussian distributed pRNG?

**Comment by giacomofiorin** [comment] 2015-10-13 16:25
No, I think the uniform distribution is appropriate for this particular use here.  In other cases, the Gaussian-distributed number may be converted back into a uniform one through the use of erf().  Then again, the uniform pRNGs are being used almost always, and Gaussian numbers are then obtained through the Box-Muller transformation.  So a uniform pRNG is indeed already available for NAMD and LAMMPS.

The main issue I see here is that VMD doesn't have a good pRNG at the moment: I'm actually wondering whether to stop using it in colvarproxy_vmd at all, since the pRNG is mostly used in simulation anyway.

**Comment by akohlmey** [comment] 2015-10-13 17:25
well, or you would put a decent pRNG into colvars directly. That would make the quality of the pRNG consistent across all uses.

**Comment by giacomofiorin** [comment] 2015-10-13 18:45
Yeah, I was afraid this was gonna be your suggestion :-)

Did you have a particular example in mind?  (We only need a rand_uniform() method of course, we can derive rand_gaussian() from it).

**Comment by akohlmey** [comment] 2015-10-13 19:03
It depends on how high your requirements for "quality" are and how complex a class you want to add. A widely used pRNG is the mersenne twister, but - because it is so widely used - that one has some well known weaknesses. in particular, a large state (2.5kB) that is best initialized from another pRNG, or else the initial number sequences will not differ much between different seeds. LAMMPS (currently) uses:
```c++
// Marsaglia random number generator
// see RANMAR in F James, Comp Phys Comm, 60, 329 (1990)
```
Which is much simpler to implement, has a small state and is particularly good at producing decorrelated sequences for similar seeds.
Beyond that, there are a huge number of alternatives, but i'd rather stick to something that is suitable for the specific needs and widely used and understood. At the last LAMMPS workshop we had a discussion about pRNG quality, as with the increased use of monte carlo components in LAMMPS, this becomes more relevant and a switch from RANMARS to a mersenne twister would be highly welcome by those MC users (especially, if that one could be made faster via SSE/AVX).

**Comment by giacomofiorin** [comment] 2015-10-13 19:59
Well, here I think that the size of the pRNG's state is not as critical, but whether we should store it between runs.  Up until now, we assumed that a colvars.state file would be fully portable between NAMD, LAMMPS and VMD, and that any single-point calculation would also be reproducible.  Extending that assumption to the pRNG may mean storing its state in the colvars.state file, instead of relying on the seeding mechanisms of each MD engine.

Alternatively, and more simply, we can implement the same seed across MD engines (either as default or user-provided value).  Currently, only in LAMMPS the user can set the seed for colvars, but I am in favor of extending this possibility to NAMD and VMD.

In any case, computational speed is not as big of a factor.  If you say that even in LAMMPS they are seriously considering adopting Mersenne, I don't see a reason not to add it to colvarproxy.

**Comment by akohlmey** [comment] 2015-10-13 20:06
I have implemented and tested it already two years ago.
http://git.lammps.org/git/?p=lammps-icms.git;a=blob;f=src/random_mt.cpp;hb=HEAD
Like i mentioned before, the downside of MT is that it essentially requires __another__ pRNG to not get "trapped" and create similar sequences for all seeds.

**Comment by whitead** [comment] 2015-10-13 20:13
So I've been following this discussion, as I wrote the code in question.
Just my 2 cents, but if you're worried about the state size there is a nice
implementation here that has a small state (127 bits):
https://github.com/MersenneTwister-Lab/TinyMT/tree/master/tinymt

It's maintained by the original MT authors and works nearly as well as MT
on pRNG benchmarks.

Andrew White
University of Rochester

**Comment by whitead** [comment] 2015-10-13 20:16
Oh and regarding Axel's comments about the trapped problem, I think a jump
function can be used which jumps ahead N in the sequence to get away from
that issue. It's in the tinyMT (or the SIMD version SFMT for that matter).
I could be wrong about that being the same issue though:

http://www.math.sci.hiroshima-u.ac.jp/~m-mat/MT/TINYMT/JUMP/index.html

**Comment by akohlmey** [comment] 2015-11-20 21:33
Finally got around to somewhat systematically evaluating pRNGs for LAMMPS, and in the process I was alerted of the following webpage: http://www.pcg-random.org/
There is a contributed implementation for LAMMPS, that the authors might be willing to also contribute to colvars. This one claims to do away with all problems of MT and in my tests was faster, too.

**Comment by giacomofiorin** [comment] 2015-11-23 22:32
This looks quite promising, and the C++ code has several advantages:
- it compiles without any errors or warnings;
- it is a single header that can be included anywhere appropriate;
- it is documented well.

Do you have any info on the status of the paper "currently in review"?  Melissa O'Neill's page doesn't show it.

**Comment by akohlmey** [comment] 2015-11-23 22:37
No info on the paper. We cannot use the implementation on the webpage, as it is not compatible with codes like LAMMPS, but I already have an independent implementation as a LAMMPS contribution, that i tested in a standalone test package, where i am exploring pRNG options for LAMMPS.

**Comment by giacomofiorin** [comment] 2019-02-27 22:05
@akohlmey It seems that @whitead is not concerned with the use of `rand()` from the standard library. @jhenin is also saying that `abf_integrate.cpp`, which also uses `rand()`, is superseded by the runtime integrator. You OK with just closing this?

**Comment by akohlmey** [comment] 2019-02-27 22:39
@giacomofiorin if it doesn't bother you, then you can close it. My opinion on that should not be the relevant one.

**Closed** 2020-02-29 10:29 UTC
