### ISSUE TITLE
Using the output of [ cv list ] to declare a bias returns an error

### ISSUE THREAD

**Issue by flblanc** [Colvars/colvars#133] opened 2017-09-07 12:21 UTC
Dear colvars developers,

I have encountered a problem with colvars in recent nightly versions of NAMD (10th of July 17 and 7th of September 17). 

I am using the Tcl scripting interface of colvars to set up a large number of collective variables (all the phi and psi dihedrals on a ~ 20 residues alpha helix), for which I am using a for loop. This works fine and the collective variables are properly declared. However, I then wish to apply a harmonic bias on them; to declare the bias, I again use the scripting interface and notably:

`set cv_bias"`

`harmonic {`
    
    name my_bias
    colvars $cv_names
    # Then declare the other bias parameters`

`}`
`"`

where the variable `cv_names` is the output of `[ cv list ]`. The bias is then declared using `set config $cv_bias`. 

Upon execution of this code with the NAMD versions I mention above, the following error is returned:
`FATAL ERROR: Error in the collective variables module: Inappropriate ioctl for device`

I looked into it a bit more before submitting the issue and made the following observations:

- The code is executed without error and with the expected behavior on an older version of NAMD (CVS of 6th of March 17)

- The code also works on the most recent NAMD builds if `colvars $cv_names` is replaced by `colvars my_cv1 my_cv2 my_cv3 my_cv4`, that is, if I manually give the collective variable names. 

- Using the `print` command of NAMD to display `cv_bias` returns a truncated string that stops at the end of the list of collective variable names, despite the presence of more characters

- Trying to modify the output of `[ cv list ]` (for example by joining it into a string, or using the `trim` command on each of its elements) did not solve the problem.

Thus, I suspect there is a problem with the list returned by `[ cv list ]`, but I have no idea what it could be or how to solve it...
Feel free to ask for more information; if needed I can also submit a minimal version of the problematic script. 

All the best,

Florian Blanc

**Comment by jhenin** [comment] 2017-09-07 13:07
Dear Florian,

Thanks for your report. This issue was caused by a recent change that led scripting commands to return strings that included a final null character from C. This is fixed by commit 79d3164c920a9b436b5b50b2d95b074235818111

which is a single-line change in NAMD's ScriptTcl.C file.

Best,
Jerome

**Closed by jhenin** 2017-09-07 13:07 UTC

**Comment by jhenin** [comment] 2017-09-07 13:16
I have submitted the patch to NAMD:
https://charm.cs.illinois.edu/gerrit/#/c/2990/

**Comment by jhenin** [comment] 2017-09-07 15:09
@flblanc Jim merged the patch, which means you should see the fix in the next nightly build.

**Comment by giacomofiorin** [comment] 2017-09-07 19:00
@flblanc @jhenin Thank you for a very accurate report and prompt fix.

**Comment by flblanc** [comment] 2017-09-08 09:00
@jhenin @giacomofiorin 
I just tested the script with the latest nightly build and I confirm that it is now working properly. Thank you very much !
