### ISSUE TITLE
NAMD gets stuck when enabling energy minimization with CUDASOAIntegrate and Colvars

### ISSUE THREAD

**Issue by fhh2626** [Colvars/colvars#598] opened 2023-09-30 15:30 UTC
Hi, all,

I'm currently encountering a potential issue related to NAMD 3.0b4, specifically when using CUDASOAIntegrate with Colvars. This issue may be related to either NAMD or Colvars, and I'm hoping to get some understanding and possible solutions.

NAMD 3.0b4 supports using CUDASOAIntegrate with Colvars. However, when I attempt to enable both features simultaneously, NAMD gets stuck and shows `colvars: Synchronizing (emptying the buffer of) trajectory file ...`.

Interestingly, when I use CUDASOAIntegrate without enabling Colvars, or vice versa, everything is good. This leads me to believe that the issue arises specifically when both features are enabled at the same time.

Does anyone have insights into what might be causing this behavior? Any guidance or suggestions would be greatly appreciated.

Haohao

**Comment by fhh2626** [comment] 2023-10-01 03:18
You can reproduce this issue using the attached files.
[BFEE.zip](https://github.com/Colvars/colvars/files/12776039/BFEE.zip)

**Comment by jhenin** [comment] 2023-10-01 08:03
Thanks you @fhh2626 , I can reproduce this. This only occurs during minimization, so a temporary workaround is to do minimization in a separate run, without `CUDASOAintegrate`, then enable it again for dynamics. However, I am aware that it makes the workflow more complex.

I will get back to you when we make progress on this.

**Comment by fhh2626** [comment] 2023-10-01 10:31
@jhenin thanks for your reply!

**Comment by davidhardy** [comment] 2023-10-02 20:50
It is likely that this issue is due to NAMD, not Colvars. I'll be looking into it. I've created an issue for this in NAMD's repo.

**Comment by giacomofiorin** [comment] 2023-10-11 20:07
For future record, this has been fixed in the NAMD repository (3.0b5 should be the first release with the fix).

**Closed by giacomofiorin** 2023-10-11 20:07 UTC
Labels: NAMD
