### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by zwpku** [Colvars/colvars#593] opened 2023-09-27 15:05 UTC
Just report some unimportant typos.

It seems that a space is missing in the following places in the HTML manual (not sure whether this only happens to my browser).  

    - Section 6.5: 'widthcan be left as ...' 
    
    - Section 5.2, in the descriptions of both the keywords centerToReference and rotateToReference: 'onby default'
    
    - Section 4.5.3, in the description of vectorFile: 'normalizeVectionoption...' and in the description of differenceVector: 'normalizeVectoron'
    
    - Section 4.6.1, in the note: 'refPositionsand' (also appears in the PDF manual)
  
In half-harmonic potential displayed in Section 6.7 (Harmonic wall restraints), should the range where the potential is defined to be zero be better written as $\xi_{lower} \le \xi \le \xi_{upper}$?  

In line 1151 of [colvarproxy_namd.C](https://github.com/Colvars/colvars/blob/master/namd/src/colvarproxy_namd.C), cvm::log("Reguesting from NAMD...") -> "Requesting"?

**Comment by giacomofiorin** [comment] 2023-09-27 21:04
@zwpku The missing space is a formatting issue with occurrences of `\texttt{word1} word2`. I think we can tweak the doc build those but would like to know where to support it best. Can you or anybody else reproduce the issues that I describe in #580 ?

**Comment by giacomofiorin** [comment] 2023-09-27 21:04
Meanwhile, I fixed the two actual typos. Thanks!!

**Comment by zwpku** [comment] 2023-09-29 09:41
@giacomofiorin 'refPositionand' in Section 4.6.1 is produced by '\texttt{refPositions}and' in the tex file. Probably a space should be added there, i.e. '\texttt{refPositions} and'. 

The range in the harmonic potential now becomes  $\xi_{\mathrm{lower}} \geq \xi \leq \xi_{\mathrm{upper}}$. Maybe we want $\xi_{\mathrm{lower}} \leq \xi \leq \xi_{\mathrm{upper}}$ instead?

It seems that I can build the doc (which looks similar to the PDF versions on https://colvars.github.io/) under Ubuntu 20.04. Could you let me know which Mathjax formula was not rendered in your case, so that I could have a closer look?

**Comment by giacomofiorin** [comment] 2023-09-29 16:11
@zwpku Thanks! I fixed these as well (sorry I'm rushing these, trying to finish stuff up before this weekend - US gov is about to shut down).

I was also too brief in the comment about the doc build. Specifically, the HTML backend that works okay on Fedora now:

![image](https://github.com/Colvars/colvars/assets/4512089/e0121bb8-604e-452d-a640-3468719bb267)

has a few glitches on Ubuntu:

![image](https://github.com/Colvars/colvars/assets/4512089/f337b088-427d-4393-a756-8b40d6578ee6)

Here are the build steps for the PDF and HTML:
```
git clone --depth=1 git@github.com:Colvars/colvars
# Only because this is a fresh clone, trigger recompilation of the PDFs
touch colvars/doc/colvars-refman-main.tex
git clone --depth=1 git@github.com:Colvars/colvars.github.io
pushd colvars.github.io
make
```

I can't quite figure out what the glitches are triggered by, but at least they seem reproducible.

**Comment by zwpku** [comment] 2023-10-08 20:54
@giacomofiorin  I tried to build HTML on two machines, one with Ubuntu 20.04 and another with Debian 5.10. Both builds seem to have display issue with the subscripts, especially in formulas in Sections 4.4.x and 4.5.x. Also the subscripts in the inline formula correctly shown in your image are not correctly displayed in my case.

**Comment by giacomofiorin** [comment] 2023-10-16 17:39
@zwpku Thanks again for checking this. Since you followed up on the topic in another issue and the typos you pointed out are fixed, I'm closing this.

**Closed by giacomofiorin** 2023-10-16 17:39 UTC
